version: '3.1'

services:
  letschat_backend:
    container_name: 'lc_backend_api'
    image: 'allteran/letschat-backend:v.0.2'
    ports:
      - 8200:8200
    depends_on:
      - mongodb

  mongodb:
    container_name: 'mongo_db'
    restart: always
    image: mongo
    volumes:
      - ~/mongodata:/data/db
    ports:
      - 27017:27017
